import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./css/globals.css";
import AppContent from "./index";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Johan Cortes",
  description: "Generated by create next app",
};

const RootLayout = () => {
  return (
    <html lang="es">
      <AppContent font={inter} />
    </html>
  );
};

export default RootLayout;
