import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './css/globals.css'
import AppContent from '@/app/components/appContent'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Johan Cortes',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="es">
      <body className={inter.className}>
        <AppContent>
          {children}
        </AppContent>
      </body>
    </html>
  )
}
